### ISSUE TITLE
Else Case Missing in fprop?

### ISSUE THREAD

**Issue by BaLeo** [AngusG/cleverhans-attacking-bnns#1]
In the fprop method of the Conv2D layers you have a if case for binary models but i believe there is a else case missing:

```
if self.binary: 
    # center input to quantization op
    x = tf.contrib.layers.batch_norm(
          x, epsilon=BN_EPSILON, is_training=self.phase,
          reuse=reuse, scope=scope)
    self.x = self.quantize(x)
    a = tf.nn.conv2d(self.x, self.kernels, (1,) +
                               tuple(self.strides) + (1,), self.padding)
a = tf.nn.conv2d(x, self.kernels, (1,) +
                           tuple(self.strides) + (1,), self.padding)
```

So if the model is binary `x` gets quantized and used for the convolution `a`. But then in the next line `a` is overwritten with the full precision `x`. 

Writing the graph with Tensorboard you can see that there are two convolutions. There is one named "Conv2D" with quantized inputs using the "Sign" function, but that just ends. And then there is a second one named "Conv2D_1" without quantized inputs which is fed forward.

![graph_large_attrs_key _too_large_attrs limit_attr_size 1024 run](https://user-images.githubusercontent.com/37414899/37480296-23d87cf0-287f-11e8-81f5-f3d01e55b7ad.png)

If i run the script  with `python mnist_attack.py --binary --attack 2 --nb_samples 100` i get the following results:
```
Test accuracy on adversarial examples 0.5900
Avg. L_2 norm of perturbations 5.5091
Avg. rate of perturbed features 0.4964
```

If I add a else case:
```
if self.binary: 
    # center input to quantization op
    x = tf.contrib.layers.batch_norm(
          x, epsilon=BN_EPSILON, is_training=self.phase,
          reuse=reuse, scope=scope)
    self.x = self.quantize(x)
    a = tf.nn.conv2d(self.x, self.kernels, (1,) +
                               tuple(self.strides) + (1,), self.padding)
else:
    a = tf.nn.conv2d(x, self.kernels, (1,) +
                           tuple(self.strides) + (1,), self.padding)
```
the graph shows that now the quantized inputs are actually used for convolution

![graph_large_attrs_key _too_large_attrs limit_attr_size 1024 run 1](https://user-images.githubusercontent.com/37414899/37481319-b9029840-2881-11e8-93ba-485c4d9a021a.png)

but running it again i get results, that are quite different:
```
Test accuracy on adversarial examples 0.0800
Avg. L_2 norm of perturbations 6.2329
Avg. rate of perturbed features 0.5957
```

Am I missing something or is the else case actually missing?

**Comment by AngusG** [comment]
Thanks for catching this, I must have left this behind when cleaning up the code. Ideally it should be:
```
if self.binary: 
    # center input to quantization op
    x = tf.contrib.layers.batch_norm(
          x, epsilon=BN_EPSILON, is_training=self.phase,
          reuse=reuse, scope=scope)
    x = self.quantize(x)
x = tf.nn.conv2d(x, self.kernels, (1,) +
                           tuple(self.strides) + (1,), self.padding)
```
I can't recall why I was assigning x as a class variable, there's no need for this so i'm removing it, along with summaries which similarly don't need to be attached to the layer.
